# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.cache/wt} [current_project]
set_property parent.project_path {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo {c:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/new/CONTMAQ.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/imports/new/Cont.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/new/Cont_32.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/imports/new/DIV_100K.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/imports/new/DIV_1M.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/imports/new/DIV_200K.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/imports/new/Deco_3a8.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/imports/new/Deco_hexa.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/new/Detector.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/new/FMS.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/new/Memoria_32x16.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/imports/new/RAM2.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/new/Reg_univ.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/new/Unit_control.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/imports/new/Visualiza.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/new/cont_leer.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/new/cont_mux.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/new/div.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/new/mux_16.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/imports/new/mux_4a1.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/imports/new/mux_8a1.vhd}
  {C:/Users/jabid/Documents/Universidad/Tarea/Detector de secuencia/Detector de secuencia.srcs/sources_1/new/main.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
